name: Deploy Service

on:
 
  push:
    branches: [ master, main ]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      TF_WORKSPACE: dev
    defaults:
      run:
        working-directory: ./deployment
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Terraform fmt
      id: fmt
      run: |
        terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: |
        terraform init

    - name: Terraform Validate
      id: validate
      run: |
        terraform validate -no-color
      continue-on-error: false

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -input=false
      continue-on-error: false

    - run: echo ${{ steps.plan.outputs.stdout }}
    - run: echo ${{ steps.plan.outputs.stderr }}
    - run: echo ${{ steps.plan.outputs.exitcode }}

    - name: Terraform Apply
      id: apply
      run: |
        terraform apply -input=false -auto-approve
      continue-on-error: false

    - run: echo ${{ steps.apply.outputs.stdout }}
    - run: echo ${{ steps.apply.outputs.stderr }}
    - run: echo ${{ steps.apply.outputs.exitcode }}  