name: Deploy Service

on:
 
  push:
    branches: [ master, main ]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Terraform fmt
      id: fmt
      run: |
        terraform workspace select z-infra
        terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: |
        terraform workspace select z-infra
        terraform init

    - name: Terraform Validate
      id: validate
      run: |
        terraform workspace select z-infra
        terraform validate -no-color

    - name: Terraform Apply
      id: apply
      run: |
        terraform workspace select z-infra
        terraform -input=false -auto-approve
      continue-on-error: true